name: workspace-release
description: "Dry-run or publish Rust workspace crates using cargo"

inputs:
  mode:
    description: "Release mode: dry-run or publish"
    required: true
    default: "dry-run"
  verify-main-head:
    description: "If true, ensure the triggering SHA matches main's HEAD"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Verify tag matches main HEAD
      if: ${{ inputs.verify-main-head == 'true' }}
      shell: bash
      run: |
        git fetch origin main --depth=1
        main_sha="$(git rev-parse origin/main)"
        tag_sha="$(git rev-parse HEAD)"

        echo "main_sha=$main_sha"
        echo "tag_sha=$tag_sha"

        if [ "$main_sha" != "$tag_sha" ]; then
          echo "::error::The release/tag commit does not match origin/main HEAD. Aborting."
          exit 1
        fi

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry and git index
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Cleanup large tools for build space
      uses: ./.github/actions/cleanup-runner

    - name: Install cargo-binstall
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall

    - name: Install cargo-msrv
      shell: bash
      run: cargo binstall --no-confirm --force cargo-msrv

    - name: Check MSRV
      shell: bash
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        ./scripts/check-msrv.sh

    - name: Clean packaging directory
      shell: bash
      run: rm -rf target/package

    # Workaround for cargo#14283, cargo#14789
    - name: Clear cargo registry
      if: ${{ inputs.mode == 'dry-run' }}
      shell: bash
      run: rm -rf ~/.cargo/registry/{cache,index,src}

    - name: Dry-run workspace publish
      if: ${{ inputs.mode == 'dry-run' }}
      shell: bash
      run: cargo publish --workspace --dry-run

    - name: Publish workspace crates
      if: ${{ inputs.mode == 'publish' }}
      shell: bash
      env:
        CARGO_REGISTRY_TOKEN: ${{ env.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --workspace
