[package]
name = "p3-miden-blake3-air"
description = "Blake3 compression AIR tailored for 192-bit digests (fewer output columns than p3-blake3-air)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
homepage.workspace = true

[dependencies]
p3-air.workspace = true
p3-field.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
itertools = { version = "0.14", default-features = false }
rand.workspace = true
tracing.workspace = true
