[package]
description  = "Shared development utilities (benchmarks, test fixtures) for p3-miden crates"
edition      = "2024"
homepage     = "https://github.com/0xMiden/p3-miden"
license      = "MIT OR Apache-2.0"
name         = "p3-miden-dev-utils"
readme       = "../README.md"
repository   = "https://github.com/0xMiden/p3-miden"
rust-version = "1.90"
version      = "0.5.1"

[dependencies]
# Internal
p3-miden-stateful-hasher.workspace = true

# Plonky3
p3-blake3.workspace     = true
p3-challenger.workspace = true
p3-field.workspace      = true
p3-goldilocks.workspace = true
p3-keccak.workspace     = true
p3-matrix.workspace     = true
p3-symmetric.workspace  = true

# Third-party
rand.workspace = true

[features]
parallel = []

[lints]
workspace = true
