[profile.default]
default-filter = 'not (test(merkle::smt::full::concurrent) or test(merkle::smt::full::large) or binary(rocksdb_large_smt))'
fail-fast      = false
failure-output = "immediate-final"

[profile.smt-concurrent]
default-filter = 'test(merkle::smt::full::concurrent)'
fail-fast      = false
failure-output = "immediate-final"

[profile.large-smt]
default-filter = '(test(merkle::smt::full::large) or binary(rocksdb_large_smt))'
fail-fast      = false
failure-output = "immediate-final"
