[profile.default]
default-filter = 'not test(merkle::smt::full::concurrent)'
fail-fast      = false
failure-output = "immediate-final"

[profile.smt-concurrent]
default-filter = 'test(merkle::smt::full::concurrent)'
fail-fast      = false
failure-output = "immediate-final"
