# Runs linting related jobs.

name: lint

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clippy:
    name: clippy nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install LLVM/Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17"
      - name: Clippy
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add clippy
          make clippy

  rustfmt:
    name: rustfmt check nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
          make format-check

  doc:
    name: doc stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install LLVM/Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17"
      - name: Build docs
        run: |
          rustup update --no-self-update
          make doc
