# Runs linting related jobs (local copy with LLVM for clippy/doc).

name: lint

on:
  push:
    branches: [ main, next ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: typos
      - run: make typos-check

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', inputs.target_branch) }}
      - name: Fmt
        run: make format-check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Added: LLVM/Clang for RocksDB/bindgen
      - name: Install LLVM/Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17"
      - name: Rustup
        run: |
          rustup update --no-self-update
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', inputs.target_branch) }}
      - name: Clippy
        run: make clippy

  toml:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: make toml-check

  workspace-lints:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspace-lints
      - run: |
          make workspace-check

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Added: LLVM/Clang for RocksDB/bindgen
      - name: Install LLVM/Clang
        uses: ./.github/actions/install-llvm
        with:
          version: "17"
      - name: Rustup
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', inputs.target_branch) }}
      - name: Build docs
        run: make doc

  unused_deps:
    name: check for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: machete
        uses: bnjbvr/cargo-machete@main