# Runs linting related jobs.

name: lint

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    uses: 0xMiden/.github/.github/workflows/lint.yml@main
