name: Workspace release dry-run

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: read
  id-token: write

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release-dry-run:
    if: ${{ github.repository_owner == '0xMiden' }}
    uses: 0xMiden/.github/.github/workflows/workspace-release.yml@ci/reusable-workspace-release
    with:
      mode: dry-run
      msrv_script_path: scripts/check-msrv.sh
      cargo_msrv_toolchain: 1.91
